trigger: none

variables:
  acrName: dwimicroservices.azurecr.io
  imageName: order-service

pool:
  name: 'dwipool'
  demands:
    - agent.name -equals dwiagent

stages:

# ==================================================
# 1️⃣ BUILD STAGE
# ==================================================
- stage: Build
  displayName: Build & Push
  jobs:
  - job: BuildJob
    steps:

    - checkout: self

    - script: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        cd order-service
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        echo "Running unit tests..."
      displayName: Run Tests

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: 'dockersvn_WI'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: order-service/Dockerfile
        tags: |
          $(Build.BuildId)

    - script: |
        mkdir -p build
        echo "{ \"image\": \"$(imageName)\", \"tag\": \"$(Build.BuildId)\" }" > build/build-info.json
      displayName: Create Build Info

    - publish: build
      artifact: build-info


# ==================================================
# 2️⃣ DEV DEPLOY
# ==================================================
- stage: Deploy_Dev
  dependsOn: Build
  jobs:
  - deployment: DevDeploy
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: build-info

          # 🔥 Extract tag properly with output variable
          - script: |
              TAG=$(cat $(Pipeline.Workspace)/build-info/build/build-info.json | jq -r .tag)
              echo "Extracted tag: $TAG"
              echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$TAG"
            name: ExtractTag
            displayName: Extract Image Tag

          - task: KubernetesManifest@1
            displayName: Deploy to Dev
            inputs:
              action: deploy
              kubernetesServiceConnection: aks_dev_sp
              namespace: dev
              manifests: order-service/k8s/dev.yaml
              containers: |
                $(acrName)/$(imageName):$(ExtractTag.IMAGE_TAG)


# ==================================================
# 3️⃣ QA DEPLOY
# ==================================================
- stage: Deploy_QA
  dependsOn: Deploy_Dev
  jobs:
  - deployment: QADeploy
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: build-info

          - script: |
              TAG=$(cat $(Pipeline.Workspace)/build-info/build/build-info.json | jq -r .tag)
              echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$TAG"
            name: ExtractTag
            displayName: Extract Image Tag

          - task: KubernetesManifest@1
            displayName: Deploy to QA
            inputs:
              action: deploy
              kubernetesServiceConnection: aks_qa_sp
              namespace: qa
              manifests: order-service/k8s/qa.yaml
              containers: |
                $(acrName)/$(imageName):$(ExtractTag.IMAGE_TAG)


# ==================================================
# 4️⃣ UAT DEPLOY
# ==================================================
- stage: Deploy_UAT
  dependsOn: Deploy_QA
  jobs:
  - deployment: UATDeploy
    environment: uat
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: build-info

          - script: |
              TAG=$(cat $(Pipeline.Workspace)/build-info/build/build-info.json | jq -r .tag)
              echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$TAG"
            name: ExtractTag
            displayName: Extract Image Tag

          - task: KubernetesManifest@1
            displayName: Deploy to UAT
            inputs:
              action: deploy
              kubernetesServiceConnection: aks_uat_sp
              namespace: uat
              manifests: order-service/k8s/uat.yaml
              containers: |
                $(acrName)/$(imageName):$(ExtractTag.IMAGE_TAG)


# ==================================================
# 5️⃣ PROD DEPLOY
# ==================================================
- stage: Deploy_Prod
  dependsOn: Deploy_UAT
  jobs:
  - deployment: ProdDeploy
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: build-info

          - script: |
              TAG=$(cat $(Pipeline.Workspace)/build-info/build/build-info.json | jq -r .tag)
              echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$TAG"
            name: ExtractTag
            displayName: Extract Image Tag

          - task: KubernetesManifest@1
            displayName: Deploy to Prod
            inputs:
              action: deploy
              kubernetesServiceConnection: aks_prod_sp
              namespace: prod
              manifests: order-service/k8s/prod.yaml
              containers: |
                $(acrName)/$(imageName):$(ExtractTag.IMAGE_TAG)
