trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main

variables:
  acrName: dwimicroservices.azurecr.io
  imageName: order-service
  imageTag: $(Build.SourceVersion)

pool:
  name: 'dwipool'
  demands:
    - agent.name -equals dwiagent

steps:

- checkout: self



- script: |
    python3 -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    cd order-service
    pip install -r requirements.txt
  displayName: Install Dependencies in venv

- script: |
    echo "Running unit tests..."
  displayName: Run Tests

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'dockersvn_WI'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      $(imageTag)

# Create artifact metadata
- script: |
    mkdir -p build
    echo "{ \"image\": \"$(imageName)\", \"tag\": \"$(imageTag)\" }" > build/build-info.json
  displayName: Create Build Info

- publish: build
  artifact: build-info


- task: KubernetesManifest@1
  displayName: Deploy to Dev
  inputs:
    action: deploy
    kubernetesServiceConnection: aks_dev_sp
    namespace: dev
    manifests: order-service/k8s/dev.yaml
    containers: |
      dwimicroservices.azurecr.io/order-service:$(imageTag)
