trigger:
  branches:
    include:
      - feature/*

pr: none

variables:
  acrName: dwimicroservices.azurecr.io
  imageName: order-service

pool:
  name: 'dwipool'
  demands:
    - agent.name -equals dwiagent

stages:

- stage: Build_And_Deploy_Dev
  jobs:
  - job: BuildAndDeploy
    steps:

    - checkout: self

    - script: |
        echo "Installing dependencies"
        cd order-service
        pip install -r requirements.txt
      displayName: Install Dependencies

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: 'dockersvn_WI'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: order-service/Dockerfile
        tags: |
          $(Build.SourceBranchName)

    - script: |
        IMAGE="$(acrName)/$(imageName):$(Build.SourceBranchName)"
        echo "Deploying $IMAGE to Dev"

        kubectl apply -f order-service/k8s/dev.yaml -n dev
        kubectl set image deployment/order-service \
          order-service=$IMAGE \
          -n dev

        kubectl rollout status deployment/order-service -n dev
      displayName: Deploy to Dev
